<?php

    tcpdf();
    // create new PDF document
    //$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
    //$pdf = new TCPDF("P", PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
    $pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

    // set document information
    $pdf->SetCreator(PDF_CREATOR);
    $pdf->SetTitle("Enrollment Summary");
    
    // set margins
    $pdf->SetMargins(10, 20 , 10);
    $pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
    $pdf->SetFooterMargin(PDF_MARGIN_FOOTER);
    $pdf->SetFont('helvetica','',10);
    //$pdf->SetAutoPageBreak(TRUE, 6);
    
   //font setting
    //$pdf->SetFont('calibril_0', '', 10, '', 'false');
    
    $pdf->setPrintHeader(false);
    $pdf->setPrintFooter(false);
    // Add a page
    // This method has several options, check the source code documentation for more information.
    $pdf->AddPage('P', 'LEGAL');            

    
    
    // Set some content to print
    $html = '<table border="0" cellspacing="0" cellpadding="1" style="color:#333; font-size:9;">
            <tr>                            
                <td width="100%" style="text-align: center; border-bottom:1px solid #333">             
                    <font style="font-family:Calibri Light; font-size: 11;font-weight: bold;">Enrollment Summary for '.$sem['enumSem'].' Term SY'.$sem['strYearStart'].'-'.$sem['strYearEnd'].'</font>
                </td>
            </tr>        
            </table>
           ';
    



$html .= '       
     <br />
     <table v-if="enrolled" class="table table-bordered table-striped">
     <tr>
         <th style="width:40%;font-size:9px;">Program</th>
         <th style="width:10%;font-size:9px;">Freshman</th>
         <th style="width:10%;font-size:9px;">Transferee</th>
         <th style="width:10%;font-size:9px;">Foreign</th>
         <th style="width:10%;font-size:9px;">SD</th>
         <th style="width:10%;font-size:9px;">Continuing</th>
         <th style="width:10%;font-size:9px;">Total</th>
     </tr>
     <tr style="line-height:10px;">
        <th colspan="6"></th>
     </tr>
     ';
     
     $all_enrolled = 0;
    foreach($enrollment as $item){        
        $major = ($item['strMajor'] != "None" && $item['strMajor'] != "")?'Major in '.$item['strMajor']:''; 
        $all_enrolled +=  $item['enrolled_freshman'] + $item['enrolled_transferee'] + $item['enrolled_foreign'] + $item['enrolled_second'] + $item['enrolled_continuing'];
        $html .= '            
            <tr>
                <td style="font-size:8px;">'.trim($item['strProgramDescription']).' '.$major.'</td>
                <td style="font-size:8px;">
                    '.$item['enrolled_freshman'].'
                </td>
                <td style="font-size:8px;">
                    '.$item['enrolled_transferee'].'
                </td>
                <td style="font-size:8px;">
                    '.$item['enrolled_foreign'].'
                </td>
                <td style="font-size:8px;">
                    '.$item['enrolled_second'].'
                </td>
                <td style="font-size:8px;">
                    '.$item['enrolled_continuing'].'
                </td>
                <td style="font-size:8px;">
                    '.($item['enrolled_freshman'] + $item['enrolled_transferee'] + $item['enrolled_foreign'] + $item['enrolled_second'] + $item['enrolled_continuing']).'
                </td>
            </tr>
            <tr style="line-height:5px;">
                <th colspan="6"></th>
            </tr>
            ';
    }
$html .= ' 
    <tr style="line-height:10px;">
        <th style="border-top:1px solid #333;" colspan="6"></th>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td><strong>&nbsp;'.$all_enrolled.'</strong></td>
    </tr>
    <tr style="line-height:30px;">
        <th colspan="6"></th>
    </tr>
    <tr style="text-align:center;">
        <td>GENERATED BY: '.$user['strFirstname']." ".$user['strLastname'].'</td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr style="text-align:center;">
        <td>RUNDATE&TIME:'.date('Y-m-d h:i a').'</td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
 </table>
 
 '; 
  
            
$pdf->writeHTML($html, true, false, true, false, '');

//$pdf->writeHTMLCell(0, 0, '', '', $html, 0, 1, 0, true, '', true);

// ---------------------------------------------------------

// Close and output PDF document
// This method has several options, check the source code documentation for more information.
$pdf->Output("enrollmentSummary".date("Ymdhis").".pdf", 'I');


?>