<table border="0" cellspacing="0" cellpadding="1" style="color:#333; font-size:9;">
            <tr>
                <td width="100%" style="text-align:center">             
                    <font style="font-family:Calibri Light; font-size: 11;font-weight: bold;">Enrollment Summary for <?php echo $sem['enumSem'].' Term SY'.$sem['strYearStart'].'-'.$sem['strYearEnd']; ?></font>
                </td>
            </tr>
            <tr>
                <td width="100%" style="text-align:center">Enrollment Statistics</td>
            </tr>
            <tr><td></td></tr>
            <tr>
                <td>Address: <?php echo $campus_address; ?> </td>
            </tr>
            <tr>
                <td>Institutional Identifier No.: 13315</td>
            </tr>
            <tr>
                <td>Term/SY: <?php echo $sem['enumSem'] . ' Term SY' . $sem['strYearStart'] . '-' . $sem['strYearEnd']; ?></td>
            </tr>
            <tr style="line-height:10px;">
                <td style="border-top:1px solid #333;" colspan="9"></td>
            </tr>
            </table>
            <br />
    <table class="table table-bordered table-striped">
     <tr>
        <td style="font-size:9px;">Program</td>';
        <?php foreach($student_years as $year): ?>
            <td style="font-size:9px;">ID<?php echo $year; ?></td>
        <?php endforeach; ?>
            <td><strong>Total</strong></td></tr>
     <tr style="line-height:10px;">
        <td colspan="9"></td>
     </tr>
    
    <?php foreach($enrollment as $item):
        $total_per_program = 0; 
        $major = ($item['strMajor'] != "None" && $item['strMajor'] != "")?'Major in '.$item['strMajor']:''
    ?>
        <tr><td style="font-size:9px;"><?php echo $item['strProgramDescription'] . ' ' . $major; ?></td>
        <?php foreach($student_years as $year):  
            $total_per_program += $item['years'][$year];
        ?>
            <td style="font-size:8px;"><?php echo $item['years'][$year]; ?></td>
        <?php endforeach; ?>
                
        <td style="font-size:8px;"><?php echo $total_per_program; ?></td></tr>
            <tr style="line-height:5px;">
                <th colspan="7"></th>
            </tr>
    <?php endforeach; ?>

    <tr style="line-height:10px;">
        <th style="border-top:1px solid #333;" colspan="9"></th>
    </tr>
    <tr><td></td>

    <?php foreach($enrolled_per_year as $yearly): ?>
        <td><?php echo $yearly; ?></td>
    <?php endforeach; ?>

    <td><strong>&nbsp;<?php echo $total_enrolled; ?></strong></td></tr>
    <tr style="line-height:30px;">
        <th colspan="8"></th>
    </tr>
    <tr style="text-align:center;">
        <td>GENERATED BY: <?php echo $user['strFirstname'] . ' ' . $user['strLastname']; ?></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr style="text-align:center;">
        <td>Date and Time Printed: <?php echo date('F d, Y h:i A'); ?></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
 </table>
?>