<table border="0" cellspacing="0" cellpadding="0" style="color:#333; font-size:9;">            
            <tr>            
                <td colspan = "3" width="100%" style="text-align: center;">             
                    
                </td>
            </tr>            
            <tr>
                <td colspan="3" align="center" style="text-align:center;vertical-align: bottom"><img src= "https://i.ibb.co/xL1WcSm/iac-cebu.png"  width="120" /></td>        
            </tr>            
<table border="0">    
    <tr style="line-height:12px;">
        <td style="font-size:9px;text-align:center;letter-spacing:5px;"><b>FACULTY LOAD <FORM:post></FORM:post></b></td>
    </tr>
    
    <tr style="line-height:10px;">
        <td style="font-size:9px;text-align:center"><?php echo  $sem['enumSem']." Term, ".$sem['strYearStart'] . "-" . $sem['strYearEnd']; ?></td>
    </tr>
    <tr style="line-height:10px;">
        <td style="font-size:9px;text-align:center"></td>
    </tr>
</table>
<table>    
    <tr style="line-height:10px;">
        <td colspan="7"></td>        
    </tr>  
</table>
<table border="0" cellpadding="2px">
    <tr>
        <td width="20%"><strong>NAME OF INSTRUCTOR</strong></td>
        <td width="1%" style="text-align:right">:</td>
        <td width="40%" style="border-bottom:1px solid #333;"><?php echo $faculty['strLastname'].", ".$faculty['strFirstname']." ".$faculty['strMiddlename']; ?></td>
    </tr>
    <tr>
        <td width="20%"><strong>EMPLOYEE NUMBER</strong></td>
        <td width="1%;" style="text-align:right">:</td>
        <td width="40%" style="border-bottom:1px solid #333;"><?php echo $faculty['strFacultyNumber']; ?></td>
    </tr>
</table>
<table>    
    <tr style="line-height:10px;">
        <td colspan="7"></td>        
    </tr>  
</table>
<table border="1" cellpadding="2px">    
    <tr style="line-height:16px;text-align:center;">                        
        <th style="font-size:8px;" width="30%"><b>Subject(s)</b></th>
        <th style="font-size:8px;" width="10%"><b>Subject Code</b></th>
        <th style="font-size:8px;" width="10%"><b>Section</b></th>
        <th style="font-size:8px;" width="5%"><b>Days</b></th>
        <th style="font-size:8px;" width="10%"><b>Time</b></th>
        <th style="font-size:8px;" width="10%"><b>Room</b></th>
        <th style="font-size:8px;" width="5%"><b>Units</b></th>
        <th style="font-size:8px;" width="20%"><b>No. of Students</b></th>
    </tr>
<?php 
$hgt = 265; 
foreach($classlists as $classlist): 
    $hgt -= 15;
?>
    
    <tr style="line-height:12px;">        
        <td  style="font-size:8px;"><?php echo $classlist['subjectDescription']; ?></td>
        <td  style="font-size:8px;"> <?php echo $classlist['strCode']; ?></td>        
        <td  style="font-size:8px;text-align:center;"><?php echo $classlist['strClassName'].$classlist['year'].$classlist['strSection']." ".$classlist['sub_section']; ?></td>
        <td  style="font-size:8px;text-align:center;"><?php echo $classlist['sched_day']; ?></td>
        <td  style="font-size:8px;text-align:center;"><?php echo $classlist['sched_time']; ?></td>
        <td  style="font-size:8px;text-align:center;"><?php echo $classlist['sched_room']; ?></td>        
        <td  style="font-size:8px;text-align:center;"><?php echo $classlist['strUnits']; ?></td>            
        <td  style="font-size:8px;text-align:center;"><?php echo $classlist['slots_taken_enrolled']; ?></td>
    </tr>
   <?php        
    endforeach; ?>    
</table>
<table>    
    <tr style="line-height:<?php echo $hgt; ?>px">
        <td colspan="7"></td>        
    </tr>  
</table>
<table border="0" cellpadding="2px" style="font-size:8px;border-spacing: 15px 0;">
    <tr>
        <td width="22%">ENDORSED BY:</td>
        <td width="22%">APPROVED BY:</td>
        <td width="22%"></td>
        <td width="22%">Conforme:</td>        
    </tr>
    <tr style="line-height:20px;">
        <td colspan="4"></td>        
    </tr>  
    <tr style="text-align:center;">
        <td style="border-top:1px solid #333"><strong>PROGRAM CHAIR</strong></td>
        <td style="border-top:1px solid #333"><strong>DEAN</strong></td>
        <td style="border-top:1px solid #333"><strong>VP ACADEMIC AFFAIRS</strong></td>
        <td style="border-top:1px solid #333"><strong>FACULTY MEMBER</strong></td>
    </tr>
    <tr style="line-height:20px;">
        <td colspan="4"></td>        
    </tr>  
    <tr style="text-align:center;">
        <td style="border-top:1px solid #333">Date</td>
        <td style="border-top:1px solid #333">Date</td>
        <td style="border-top:1px solid #333">Date</td>
        <td style="border-top:1px solid #333">Date</td>
    </tr>
    <tr style="line-height:10px;">
        <td colspan="4"></td>        
    </tr> 
    <tr style="text-align:center;">
        <td>GENERATED BY: <?php echo $user['strFirstname']." ".$user['strLastname']; ?></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr style="text-align:center;">
        <td>RUNDATE&TIME: <?php echo date('Y-m-d h:i a'); ?></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
</table>